name: ci

on:
  push:
    branches: [ dev ]
    paths:
      - 'staging_build_num.txt'

jobs:

  test-unit:
    timeout-minutes: 15

    runs-on: ${{ matrix.os }}
    if: ${{ !contains(github.event.head_commit.message, 'Merge remote-tracking branch') }}

    strategy:
      matrix:
        os: [ ubuntu-latest ] # windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: gradle

      - name: Run unit tests
        run: gradle fullTest --no-daemon --info

  test-as-dependency:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ] # windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: gradle

      - name: Warm up gradle
        # so it will not show "..........10%.." when called again
        run: ./gradlew pkgver -q

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Build sample project that uses the library
        run: |
          pip install git+https://github.com/rtmigo/tempp_py
          python test_as_dependency.py dev

  to-staging:
    needs: [test-unit, test-as-dependency]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge current -> staging
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          target_branch: staging
          github_token: ${{ github.token }}

  publish-flag:
    if: github.event.head_commit.message=='publish'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

  to-master:
    needs: [ to-staging, publish-flag ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge to master branch
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          target_branch: master
          github_token: ${{ github.token }}

  to-github-release:
    needs: [ to-staging, publish-flag ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: gradle

      - name: Build binaries (with testing)
        run: |
          ./gradlew build --no-daemon

      # ADD GITHUB RELEASE
      - name: Warm up gradle
        # so it will not show "..........10%.." when called again
        run: ./gradlew pkgver -q

      - name: Get the project version
        run: echo "PKGVER=$(./gradlew pkgver -q)" >> $GITHUB_ENV

      - name: Publish GitHub release
        id: publish_github_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.PKGVER }}
          files: ./build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
